version: '3.7'

services:
  consul:
    command: -server -bootstrap -rejoin 
    image: progrium/consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
  micro:
    command: --registry_address=consul:8500 api --handler=rpc
    image: microhq/micro:latest
    depends_on:
      - consul
      - api
    ports:
      - "8080:8080"
  api:
    build: ./api/hotel
    command: --registry_address=consul:8500
    depends_on:
      - consul
      - auth
      - geo
      - profile
      - rate
  auth:
    build: ./srv/auth
    command: --registry_address=consul:8500
    networks:
      - service-discovery
  geo:
    build: ./srv/geo
    command: --registry_address=consul:8500
    networks:
      - service-discovery
  profile:
    build: ./srv/profile
    command: --registry_address=consul:8500
    networks:
      - service-discovery
  rate:
    build: ./srv/rate
    command: --registry_address=consul:8500
    networks:
      - service-discovery

networks:
  service-discovery:
